### PR TITLE
Custom heroes are now addressed by their name, default illusion spells will spawn correct hero

### PR DESCRIPTION
**Pull request by Celireor**
- [X] Correct custom hero name is displayed everywhere (when display names over healthbar - hero names is selected, when hovering over allied/enemy custom hero to see their name, etc)
- [X] Default illusion producing spell produces custom heroes instead of hero base (still will not gain shard bonus)

### CODE REVIEW

**Comment by ark120202** [comment]
Copy-pasting hero definitions to another file is definitely not a option.
Won't calling `TransformUnitClass` on standard illusions work?
In a worst case rewriting all illusion abilities would look neater then duplicating 1k lines of code.

> Correct custom hero name is displayed everywhere

It's interesting.  Health bars would be covered by #13, but what else it includes? Voice chat hero images? Kill streak announcements? Minimap icons?

**Comment by Celireor** [comment]
Hovering over the unit to see his hero

**Comment by ark120202** [comment]
So, to summarize
Pros:
- We're using SetUnitName, which appears to be more correct than current solution for unit name. That means we can remove GetFullName and simplify networking.
- Correct names above healthbars (solved by #13)
- Correct names on hover (also should be solved by some panorama hack, or all these values can be moved to healthbar)

Cons:
- The base_hero modified with TransformUnitClass isn't the same as a completely new unit. Even though it may be not visible in-game, there may be things that aren't handled (like voices) or handled incorrectly.
- We're losing correct inheritance, from base_hero. It may work for now but definitely would be a pain to update. That may be fixed by creating a build plugin for new build pipleline coming in 2.0.0, but it's still not good enough.

Tell me if I have missed something, but rewriting all illusion abilities + implementing #13 looks like a neater solution.

**Comment by ark120202** [comment]
Closing for now, since rewriting looks better.

**Pull request closed without merging**
