### PR TITLE
Attempt to fix meta bug

### PR DESCRIPTION
**Pull request by Celireor**

### CODE REVIEW

**Comment by ark120202** [comment]
Is there an issue about this bug?

**Comment by Celireor** [comment]
Hard to duplicate, requires frame-perfect timing as well as unlucky dedicated server

You basically need to get really unlucky with the event multithreading to duplicate this after the fix (i hope, it was hard to duplicate before)

**Comment by ark120202** [comment]
I think there was a command to make a fake ping.
Still, even if it's hard to reproduce I'd like to have some details.

I guess it's something with not teleporting players while they were changing a hero?
In that case whole `unit.Teleport` method should be fixed. Maybe save `unit.TeleportPosition` before changing hero and run `unit:Teleport(teleportPosition)` after?

**Comment by Celireor** [comment]
Changing heroes actually delete the old hero before creating the new one

**Comment by Celireor** [comment]
Changed mechanism for preventing the bug

**Comment by ark120202** [comment]
Teleport function already saves position in `unit.TeleportPosition`, why add another field?

**Pull request closed without merging**
