### PR TITLE
Give Saitama a beautiful portrait

### PR DESCRIPTION
**Pull request by Celireor**

### CODE REVIEW

**Comment by Celireor** [comment]
stegius gets 1 too

**Comment by ark120202** [comment]
Nice work!
You should rename `arenaportraits` to `portraits` to match other directory names.
Isn't `portraits` [supposed to be](https://github.com/SteamDatabase/GameTracking-Dota2/blob/master/game/dota/pak01_dir/scripts/npc/portraits.txt) `portraits.txt`?
I don't really like the idea of storing Dota file locally. It would be nice to sync it on the build step. Well, I think I'll make it in v2.0.0.

Just interesting, what have you used to make them? I think `dota_portrait_debug_mode 1` stopped working in Source 2.

**Comment by Celireor** [comment]
go merge
i can always add more later

**Comment by ark120202** [comment]
```
	"Version"		"1"
	"PreferModelNames"		"1"
	"DefaultActivity"		"ACT_DOTA_CAPTURE"
	"CannotChangeActivity"		"1"
```
Is that used somewhere in dota?

**Comment by Celireor** [comment]
I just copy pasted default portraits code

**Comment by ark120202** [comment]
Oh, right, not noticed that.
In that case I think it would be better to place it to unchanged.txt, to make it completely match current [portraits.txt](https://github.com/SteamDatabase/GameTracking-Dota2/blob/master/game/dota/pak01_dir/scripts/npc/portraits.txt), to make updates easier.

**Comment by ark120202** [comment]
I think it would make a syntax error now. KV files should have a root node:
[npc_units_custom.txt](https://github.com/ark120202/angel-arena-black-star/blob/develop/game/scripts/npc/npc_units_custom.txt)
[npc_heroes_custom.txt](https://github.com/ark120202/angel-arena-black-star/blob/develop/game/scripts/npc/npc_heroes_custom.txt)
[default_arena_base.txt](https://github.com/ark120202/angel-arena-black-star/blob/develop/game/itembuilds/default_arena_base.txt)

**Comment by Celireor** [comment]
fixed

**Pull request merged**
